include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
    sort_pub_dependencies: ignore
    avoid_redundant_argument_values: ignore
    invalid_annotation_target: ignore # freezed code generation
    cascade_invocations: ignore # isar code generation
